### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by PKJonas** [ugis90/internship#2]
1. Coordinates and MultiPolygons (Locations and Regions in your implementation) should be represented with proper classes. A coordinate has exactly two doubles, not an array of doubles;
2. It is unclear why so many parameters are nullable, because this would allow errors from a bad json file to propagate;
3. Error handling should be used - there is a lot of trust in correct json files right now, but a single bad coordinate or polygon file would make this program throw exceptions;
4. Project lacks unit tests;
5. A formatter should be used.

**Comment by ugis90** [comment]
Implemented some fixes. Would like to know if the error handling is what you had in mind. 
- Locations and Regions are represented with proper classes.
- Made most parameters immutable
- Error handling is used. Not sure if it's correct. Would appreciate feedback.
- Implemented unit tests.
- Used a formatter.
